// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/work": {
            "post": {
                "description": "Метод для отладки работы с git-ом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Тестовый метод соединения с git",
                "parameters": [
                    {
                        "description": "Параметры вызова",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Вызов прошел успешно",
                        "schema": {
                            "$ref": "#/definitions/main.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "detailed error message"
                },
                "message": {
                    "type": "string",
                    "example": "An error occurred"
                },
                "processID": {
                    "type": "string",
                    "example": "GUID"
                }
            }
        },
        "main.GitRequest": {
            "type": "object",
            "properties": {
                "repoName": {
                    "type": "string",
                    "example": "https://github.com/Lockdain/metamart.git"
                },
                "repoPassword": {
                    "type": "string",
                    "example": "password or token"
                },
                "repoUser": {
                    "type": "string",
                    "example": "elon@neof44.ru"
                }
            }
        },
        "main.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Executed successfully"
                },
                "processID": {
                    "type": "string",
                    "example": "GUID"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
