valuesSchema:
  Environment:
    type: string
    required: true
    description: Environment name used to generate environment-specific values file
  Chart.Name:
    type: string
    required: true
  Chart.Version:
    type: string
    required: true
  Chart.Description:
    type: string
    required: true
  DeploymentName:
    type: string
    required: true
  Namespace:
    type: string
    required: true

files:
  - path: Chart.yaml
    template: true
    content: |
      apiVersion: v2
      name: {{ .Chart.Name }}
      version: {{ .Chart.Version }}
      description: {{ .Chart.Description }}
      type: application

  - path: values.yaml
    template: true
    content: |
      Environment: {{ .Environment }}

      Chart:
        Name: {{ .Chart.Name }}
        Version: {{ .Chart.Version }}
        Description: {{ .Chart.Description }}

      DeploymentName: {{ .DeploymentName }}
      Namespace: {{ .Namespace }}

      Predictors:
      {{- range .Predictors }}
        - Name: {{ .Name }}
          Graph:
            Name: {{ .Graph.Name }}
            Type: {{ .Graph.Type }}
            {{- if .Graph.Implementation }}
            Implementation: {{ .Graph.Implementation }}
            {{- end }}
            {{- if .Graph.EndpointType }}
            EndpointType: {{ .Graph.EndpointType }}
            {{- end }}
            {{- if .Graph.Logger }}
            Logger:
              Mode: {{ .Graph.Logger.Mode }}
            {{- end }}
            {{- if .Graph.Children }}
            Children:
              {{- range .Graph.Children }}
              - Name: {{ .Name }}
                Type: {{ .Type }}
                Implementation: {{ .Implementation }}
                Children: []
              {{- end }}
            {{- else }}
            Children: []
            {{- end }}
      {{- end }}

  - path: values-ENV.yaml
    template: true
    content: |
      Predictors:
      {{- range .Predictors }}
        - Name: {{ .Name }}
          Replicas: {{ .Replicas }}
          Traffic: {{ .Traffic }}
          SvcOrchEnv:
          {{- range .SvcOrchEnv }}
            - Name: {{ .Name }}
              {{- if .Value }}
              Value: {{ .Value }}
              {{- else if .ValueFrom }}
              ValueFrom:
                SecretKeyRef:
                  Name: {{ .ValueFrom.SecretKeyRef.Name }}
                  Key: {{ .ValueFrom.SecretKeyRef.Key }}
              {{- end }}
          {{- end }}
          Graph:
            {{- if .Graph.ModelUri }}
            ModelUri: {{ .Graph.ModelUri }}
            {{- end }}
            {{- if .Graph.Children }}
            Children:
              {{- range .Graph.Children }}
              - ModelUri: {{ .ModelUri }}
              {{- end }}
            {{- end }}
          ComponentSpec:
            ServiceAccountName: {{ .ComponentSpec.ServiceAccountName }}
            TerminationGracePeriodSeconds: {{ .ComponentSpec.TerminationGracePeriodSeconds }}
            Containers:
              {{- range .ComponentSpec.Containers }}
              - Name: {{ .Name }}
                Image: {{ .Image }}
                {{- if .Env }}
                Env:
                  {{- range .Env }}
                  - Name: {{ .Name }}
                    Value: {{ .Value }}
                  {{- end }}
                {{- end }}
                {{- if .Resources }}
                Resources:
                  Requests:
                    {{- range $k, $v := .Resources.Requests }}
                    {{ $k }}: {{ $v }}
                    {{- end }}
                  Limits:
                    {{- range $k, $v := .Resources.Limits }}
                    {{ $k }}: {{ $v }}
                    {{- end }}
                {{- end }}
                {{- if .Liveness }}
                Liveness:
                  Path: {{ .Liveness.Path }}
                  Port: {{ .Liveness.Port }}
                  InitialDelaySeconds: {{ .Liveness.InitialDelaySeconds }}
                  PeriodSeconds: {{ .Liveness.PeriodSeconds }}
                  FailureThreshold: {{ .Liveness.FailureThreshold }}
                  SuccessThreshold: {{ .Liveness.SuccessThreshold }}
                {{- end }}
              {{- end }}
      {{- end }}

  - path: templates/seldon-deployment.yaml
    template: false
    content: |
      apiVersion: machinelearning.seldon.io/v1
      kind: SeldonDeployment
      metadata:
        name: {{ .Values.DeploymentName }}
        namespace: {{ .Values.Namespace }}
      spec:
        name: {{ .Values.DeploymentName }}
        predictors:
        {{- range .Values.Predictors }}
          - name: {{ .Name }}
        {{- if .Replicas }}
            replicas: {{ .Replicas }}
        {{- end }}
        {{- if .Traffic }}
            traffic: {{ .Traffic }}
        {{- end }}
        {{- if .SvcOrchEnv }}
            svcOrchSpec:
              env:
              {{- range .SvcOrchEnv }}
                - name: {{ .Name }}
                {{- if .Value }}
                  value: {{ .Value }}
                {{- else if .ValueFrom }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .ValueFrom.SecretKeyRef.Name }}
                      key: {{ .ValueFrom.SecretKeyRef.Key }}
                {{- end }}
              {{- end }}
        {{- end }}
            graph:
              name: {{ .Graph.Name }}
              type: {{ .Graph.Type }}
              {{- if .Graph.Implementation }}
              implementation: {{ .Graph.Implementation }}
              {{- end }}
              {{- if .Graph.ModelUri }}
              modelUri: {{ .Graph.ModelUri }}
              {{- end }}
              {{- if .Graph.EndpointType }}
              endpoint:
                type: {{ .Graph.EndpointType }}
              {{- end }}
              {{- if .Graph.EnvSecretRefName }}
              envSecretRefName: {{ .Graph.EnvSecretRefName }}
              {{- end }}
              {{- if .Graph.Logger }}
              logger:
                mode: {{ .Graph.Logger.Mode }}
              {{- end }}
              {{- if .Graph.Parameters }}
              parameters:
                {{- range .Graph.Parameters }}
                - name: {{ .Name }}
                  type: {{ .Type }}
                  value: {{ .Value }}
                {{- end }}
              {{- end }}
              {{- if .Graph.Children }}
              children:
                {{- range .Graph.Children }}
                - name: {{ .Name }}
                  type: {{ .Type }}
                  {{- if .Implementation }}
                  implementation: {{ .Implementation }}
                  {{- end }}
                  {{- if .ModelUri }}
                  modelUri: {{ .ModelUri }}
                  {{- end }}
                  children: []
                {{- end }}
              {{- else }}
              children: []
              {{- end }}
        {{- with .ComponentSpec }}
            componentSpecs:
              - spec:
                {{- if .ServiceAccountName }}
                serviceAccountName: {{ .ServiceAccountName }}
                {{- end }}
                {{- if .TerminationGracePeriodSeconds }}
                terminationGracePeriodSeconds: {{ .TerminationGracePeriodSeconds }}
                {{- end }}
                containers:
                {{- range .Containers }}
                  - name: {{ .Name }}
                    {{- if .Image }}
                    image: {{ .Image }}
                    {{- end }}
                    {{- if .Env }}
                    env:
                      {{- range .Env }}
                      - name: {{ .Name }}
                        value: {{ .Value }}
                      {{- end }}
                    {{- end }}
                    {{- if .Resources }}
                    resources:
                      {{- if .Resources.Requests }}
                      requests:
                        {{- range $k, $v := .Resources.Requests }}
                        {{ $k }}: {{ $v }}
                        {{- end }}
                      {{- end }}
                      {{- if .Resources.Limits }}
                      limits:
                        {{- range $k, $v := .Resources.Limits }}
                        {{ $k }}: {{ $v }}
                        {{- end }}
                      {{- end }}
                    {{- end }}
                    {{- with .Liveness }}
                    livenessProbe:
                      httpGet:
                        path: {{ .Path }}
                        port: {{ .Port }}
                        scheme: HTTP
                      initialDelaySeconds: {{ .InitialDelaySeconds }}
                      periodSeconds: {{ .PeriodSeconds }}
                      failureThreshold: {{ .FailureThreshold }}
                      successThreshold: {{ .SuccessThreshold }}
                    {{- end }}
                    {{- with .Readiness }}
                    readinessProbe:
                      httpGet:
                        path: {{ .Path }}
                        port: {{ .Port }}
                        scheme: HTTP
                      initialDelaySeconds: {{ .InitialDelaySeconds }}
                      periodSeconds: {{ .PeriodSeconds }}
                      failureThreshold: {{ .FailureThreshold }}
                      successThreshold: {{ .SuccessThreshold }}
                    {{- end }}
                {{- end }}
        {{- end }}
        {{- end }}

  - path: .helmignore
    template: false
    content: |
      *.tgz
      .DS_Store
      .idea/
      *.swp
      __pycache__/
      .ipynb_checkpoints/
